services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval=30"
      - "--rolling-restart"
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
  reverse-proxy:
    image: traefik:v3.1
    container_name: reverse-proxy
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=sylvain.romiguier@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # http
      - "80:80"
      # https
      - "443:443"
      # web ui
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
  minimal-frontend:
    image: ghcr.io/sylvainromiguier/minimal-frontend-framework-ioc:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minimal-frontend.rule=Host(`minimal-frontend.rythmik.fr`)"
      - "traefik.http.routers.minimal-frontend.entrypoints=websecure"
      - "traefik.http.routers.minimal-frontend.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.container_name=minimal-frontend"
    container_name: minimal-frontend
    restart: unless-stopped
    networks:
      - app-network
volumes:
  letsencrypt:
    driver: local
networks:
  app-network:
