services:
  minimal-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: minimal-frontend
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
