services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: reverse-proxy
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=default"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.default.acme.email=ubuntu@rythmik.fr"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
    ports:
      # http
      - "80:80"
      # https
      - "443:443"
      # web ui
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
  minimal-frontend:
    image: ghcr.io/sylvainromiguier/minimal-frontend-framework-ioc:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minimal-frontend.entrypoints=websecure"
      - "traefik.http.routers.minimal-frontend.tls.certresolver=default"
      - "traefik.http.routers.minimal-frontend.tls=true"
      - "traefik.http.routers.minimal-frontend.tls.domains[0].main=rythmik.fr"
      - "traefik.http.routers.minimal-frontend.rule=Host(`minimal-frontend.rythmik.fr`)"
    container_name: minimal-frontend
    restart: unless-stopped
    networks:
      - app-network
volumes:
   letsencrypt:
      driver: local
networks:
  app-network:
